### ISSUE TITLE
Maestro mcz problème de communication

### ISSUE THREAD

**Issue by PeterKalel** [pipolaq/maestro#3]
Bonjour

Je viens d'installer l'addon mais quand je regarde dans les logs voici ce que j'obtiens : Sending packet PING data None
Received packet PONG data None

Et lorsque je lance l'application MCZ MEASTRO sur mon smartphone, je vois les informations du poêle revenir dans les journaux.

**Comment by SkyPhilHome** [comment]
Salut

Je remarque une petite erreur dans les instruction d'installation.
Il faut modifier le fichier _config_.py à la place de maestro.py.
Il n'y a plus rien à modifier dans maestro.py

Dans le log, ce qui est important : 
2022-02-01 22:02:46,740 :: INFO :: Attempting polling connection to http://app.mcz.it:9000/socket.io/?transport=polling&EIO=3
2022-02-01 22:02:46,745 :: DEBUG :: Starting new HTTP connection (1): app.mcz.it:9000
2022-02-01 22:02:46,813 :: DEBUG :: http://app.mcz.it:9000 "GET /socket.io/?transport=polling&EIO=3&t=1643749366.7408097 HTTP/1.1" 200 103
2022-02-01 22:02:46,815 :: INFO :: Polling connection accepted with {'sid': 'muZ1BhqiYAAj14kha-QE', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
2022-02-01 22:02:46,815 :: INFO :: Engine.IO connection established
2022-02-01 22:02:46,816 :: INFO :: Sending packet MESSAGE data 0
2022-02-01 22:02:46,816 :: INFO :: Received packet MESSAGE data 0
2022-02-01 22:02:46,817 :: INFO :: Attempting WebSocket upgrade to ws://app.mcz.it:9000/socket.io/?transport=websocket&EIO=3
2022-02-01 22:02:46,817 :: INFO :: Namespace / is connected
2022-02-01 22:02:46,818 :: INFO :: Emitting event "join" [/]
==> La connexion avec le serveur MCZ est bien établie

2022-02-01 22:02:46,895 :: INFO :: Connection en cours au broker MQTT (IP:127.0.0.1 PORT:1883)
2022-02-01 22:02:46,899 :: INFO :: Souscription au topic SUBmczPipo avec un Qos=1
2022-02-01 22:02:46,899 :: INFO :: Connecté au broker MQTT avec le code : 0
==> La connexion vers le broker MQTT est bien établie

Ensuite : 
2022-02-01 22:02:46,985 :: INFO :: Received packet MESSAGE data 2["rispondo",{"stringaRicevuta".......
==> indique une réception de données du serveur MCZ

2022-02-01 22:02:46,990 :: INFO :: Publication sur le topic MQTT PUBmczPipo le message suivant : .....
Indique un envoi de données vers le broker MQTT

2022-02-01 22:03:11,896 :: INFO :: Sending packet PING data None
2022-02-01 22:03:11,921 :: INFO :: Received packet PONG data None
sont également présent dans mon log sans interférence avec le bon fonctionnement.
Les infos sont bien présentes et rafraichies dans mon broker MQTT

**Comment by PeterKalel** [comment]
super merci beaucoup pour votre réponse et aussi rapide.
Si je comprend bien quand il y a les lignes : "Sending packet PING data None
Received packet PONG data None" c'est qu'il n'y a pas de changement d'état du poele si je comprend bien ?
J'utilise cette addon : https://github.com/SebLz/ha-addons/tree/main/maestro_gateway
Est ce que je dois modifier le fichier config.py malgré tout ? et si oui où se trouve ce fichier en question car je ne l'ai pas trouvé ?
voici ma config de l'addon :
Options

- USE_MCZ_CLOUD
- MQTT_ip
192.168.*******
- MQTT_port
1883
- MQTT_authentication
True
- MQTT_user
*******
- MQTT_pass
*******
- MQTT_TOPIC_SUB
Maestro/Command
- MQTT_TOPIC_PUB
Maestro/State
- MQTT_PAYLOAD_TYPE
TOPIC
- WS_RECONNECTS_BEFORE_ALERT
5
- MCZip
192.168.*******
- MCZport
81
- MCZ_device_serial
*******
- MCZ_device_MAC
*******
- MCZ_App_URL
http://app.mcz.it:9000

Merci pour votre aide car je dois pas être loin de faire fonctionner mon poêle

**Comment by SkyPhilHome** [comment]
Salut

En fait, le script maestro de Pipolaq et le add-on de SebLz sont 2 choses complètement différentes.
Du coup, si tu utilise le add-on, il est peut-être normal de ne pas trouver le fichier _config_.py

Si j'ai bien compris, le add-on est conçu pour HA et pas pour Jeedom. N'ayant aucune connaissance de HA, je vais avoir du mal à t'aider.

Si il n'y a pas de changement d'état, les données du poêle sont quand même reçues.
Il semble donc y avoir un soucis de connexion.

**Comment by SebLz** [comment]
Bonjour @SkyPhilHome et @PeterKalel 
En fait mon add-on ne fait qu'encapsuler dans un container HA le script présent sur ce Github, ils fonctionne donc exactement de la même manière.
Lorsqu'on configure les paramètres dans HA, l'addon écrit ces paramètres dans config.py.
Je n'ai investigué en détail mais je pense avoir déjà observé le même souci que celui évoqué ici. Après un certain temps et pour une raison que j'ignore, il arrive que le rafraichissement s'arrête et le fait de lancer l'appli MCZ semble débloquer la situation. Tout fonctionne normalement la plupart du temps pourtant.

**Comment by SkyPhilHome** [comment]
@PeterKalel , le problème serait donc une perte de connexion.  Au lancement, tu reçois bien les données en retour du serveur MCZ mais à un certains moment, plus rien ?

Pour info, les messages
2022-02-05 14:54:15,441 :: INFO :: Sending packet PING data None
2022-02-05 14:54:16,220 :: INFO :: Received packet PONG data None
viennent de l'implémentation de socketio/websocket.

Une ligne du log nous donne quelques infos : 
2022-02-01 22:02:46,815 :: INFO :: Polling connection accepted with {'sid': 'muZ1BhqiYAAj14kha-QE', 'upgrades': ['websocket'], **'pingInterval': 25000, 'pingTimeout': 5000**}
Il y a un mécanisme de heartbeat 
Il y a un ping automatique toute les 25sec (pingInterval) et on attend la réponse (PONG) pendant max 5sec (ping Timeout)
Si pas de réponse dans les 5sec, la connexion est considérée comme perdue.
Le PING/PONG est fait des 2 cotés (serveur MCZ et le client) et donc le serveur MCZ peux aussi considérer la connexion comme perdue

Il faudrait voir si dans vos log, il y aurait à un certains moment "Disconnected"
Si c'est le cas, c'est que la connexion websocket est bien perdue à un certain moment.
Le pourquoi dépend surement d'internet en général.

La solution définitive serait alors d'améliorer la gestion des déconnexions pour refaire une connexion automatiquement

**Comment by SkyPhilHome** [comment]
Salut,
SocketIO gère la reconnexion automatique.
Par contre, le code actuel envoie les commandes même si la connexion est fermée, ce qui peut causer quelques soucis.
J'ai fait des petits changement dans le code qui seront dispo après le merge de la pull request
https://github.com/pipolaq/maestro/pull/4

**Comment by SebLz** [comment]
> Salut, SocketIO gère la reconnexion automatique. Par contre, le code actuel envoie les commandes même si la connexion est fermée, ce qui peut causer quelques soucis. J'ai fait des petits changement dans le code qui seront dispo après le merge de la pull request #4

Merci pour cette update, j'ai intégré ces modifs dans l'addon HA : https://github.com/SebLz/ha-addons/commit/a9d4ae398865377d943a6aa92c78ef3325a97d6a

@PeterKalel : tu peux essayer la nouvelle version de @SkyPhilHome et voir ce que ça donne. Pour voir le log complet, tu peux utiliser Portainer:
![image](https://user-images.githubusercontent.com/190146/152679205-3747cd83-e7b4-4d28-8052-c0e99d6dec4c.png)

**Comment by PeterKalel** [comment]
Bonjour à vous deux 

Je reviens tout juste de week-end et je vois que le post  a avancé et avant tout merci pour cela car je commençais à désespérer.
Je fais la MAJ et reviens vers vous.

Merci encore

**Comment by PeterKalel** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:58:28] INFO: Launching maestro cloud connection plugin
2022-02-07 08:58:29,705 :root :: INFO :: Lancement du deamon
2022-02-07 08:58:29,706 :root :: INFO :: Anthony L. 2019
2022-02-07 08:58:29,706 :root :: INFO :: Pipolaq's version
2022-02-07 08:58:29,707 :root :: INFO :: Niveau de LOG : DEBUG
2022-02-07 08:58:29,708 :engineio.client :: INFO :: Attempting polling connection to http://app.mcz.it:9000/socket.io/?transport=polling&EIO=3
2022-02-07 08:58:29,737 :urllib3.connectionpool :: DEBUG :: Starting new HTTP connection (1): app.mcz.it:9000
2022-02-07 08:58:29,906 :urllib3.connectionpool :: DEBUG :: http://app.mcz.it:9000 "GET /socket.io/?transport=polling&EIO=3&t=1644220709.7088635 HTTP/1.1" 200 103
2022-02-07 08:58:29,909 :engineio.client :: INFO :: Polling connection accepted with {'sid': 'lY9jmeLVEuEhTWQ5pxGi', 'upgrades': ['websocket'], 'pingInterval': 25000, 'pingTimeout': 5000}
Engine.IO connection established
2022-02-07 08:58:29,910 :socketio.client :: INFO :: Engine.IO connection established
2022-02-07 08:58:29,912 :engineio.client :: INFO :: Sending packet MESSAGE data 0
2022-02-07 08:58:29,912 :engineio.client :: INFO :: Received packet MESSAGE data 0
Namespace / is connected
2022-02-07 08:58:29,914 :engineio.client :: INFO :: Attempting WebSocket upgrade to ws://app.mcz.it:9000/socket.io/?transport=websocket&EIO=3
2022-02-07 08:58:29,914 :socketio.client :: INFO :: Namespace / is connected
2022-02-07 08:58:29,941 :root :: INFO :: Connected
2022-02-07 08:58:29,943 :root :: INFO :: SID is : lY9jmeLVEuEhTWQ5pxGi
Emitting event "join" [/]
2022-02-07 08:58:29,944 :socketio.client :: INFO :: Emitting event "join" [/]
2022-02-07 08:58:29,946 :engineio.client :: INFO :: Sending packet MESSAGE data 2["join",{"serialNumber":"************","macAddress":"*************","type":"Android-App"}]
Emitting event "chiedo" [/]
2022-02-07 08:58:29,947 :socketio.client :: INFO :: Emitting event "chiedo" [/]
2022-02-07 08:58:29,949 :engineio.client :: INFO :: Sending packet MESSAGE data 2["chiedo",{"serialNumber":"***************","macAddress":"***************","tipoChiamata":0,"richiesta":"RecuperoParametri"}]
Emitting event "chiedo" [/]
2022-02-07 08:58:29,950 :socketio.client :: INFO :: Emitting event "chiedo" [/]
2022-02-07 08:58:29,951 :engineio.client :: INFO :: Sending packet MESSAGE data 2["chiedo",{"serialNumber":"*************","macAddress":"*************","tipoChiamata":1,"richiesta":"C|RecuperoInfo"}]
2022-02-07 08:58:30,129 :engineio.client :: INFO :: WebSocket upgrade was successful
2022-02-07 08:58:30,131 :engineio.client :: INFO :: Sending packet PING data None
2022-02-07 08:58:30,135 :root :: INFO :: Connection en cours au broker MQTT (IP:192.168.**.** PORT:1883)
Traceback (most recent call last):
  File "/maestro/cloud/maestro.py", line 237, in <module>
    client.connect(_MQTT_ip, _MQTT_port)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2022-02-07 08:58:30,196 :engineio.client :: INFO :: Received packet PONG data None
2022-02-07 08:58:30,258 :engineio.client :: INFO :: Received packet MESSAGE data 2["rispondo",{"stringaRicevuta":"00|0b0005233250010501010105010101010105010100000105000002010101010a0132500a46325000","socketChiamata":"lY9jmeLVEuEhTWQ5pxGi"}]
Received event "rispondo" [/]
2022-02-07 08:58:30,259 :socketio.client :: INFO :: Received event "rispondo" [/]
2022-02-07 08:58:30,259 :root :: INFO :: Received 'rispondo' message
2022-02-07 08:58:30,267 :root :: INFO :: Publication sur le topic MQTT Maestro/State le message suivant : {"Etat du poele": ["Code inconnu :", "91781347027523042834641894817091538412893000860324342555513324727753471042535950686490767544320"]}
2022-02-07 08:58:30,293 :engineio.client :: INFO :: Received packet MESSAGE data 2["rispondo",{"stringaRicevuta":"01|0b|01|00|00|007b|29|ff|00|ff|00|0087|0404|00a9|00c4|00|00|ff|00|0b|01|0085|01|01|00|01|2e|46|36|0b|010a0b|02|09|0a|07|02|07e6|006f4271|003fb9c2|000ef5b1|00040527|0000da47|00028ef9|0000|0000|03fd|0000|00|00|00|00|00|ff|ff|ff|ff|40|32|ff|ff|01","socketChiamata":"lY9jmeLVEuEhTWQ5pxGi"}]
Received event "rispondo" [/]
2022-02-07 08:58:30,298 :socketio.client :: INFO :: Received event "rispondo" [/]
2022-02-07 08:58:30,298 :root :: INFO :: Received 'rispondo' message
2022-02-07 08:58:30,301 :root :: INFO :: Publication sur le topic MQTT Maestro/State le message suivant : {"Etat du poele": "Puissance 1", "Etat du ventilateur ambiance": "Niveau 1", "Etat du ventilateur canalise 1": "Desactive", "Etat du ventilateur canalise 2": "Desactive", "Temperature des fumees": 123, "Temperature ambiante": 20.5, "Puffer Temperature": 255, "Temperature chaudiere": 0, "Temperature NTC3": 255, "Etat de la bougie": "Ok", "ACTIVE - Set": 135, "RPM - Ventilateur fummees": 1028, "RPM - Vis sans fin - SET": 169, "RPM - Vis sans fin - LIVE": 196, "Brazero": ["Code inconnu :", "255"], "Profil": "Manuel", "Etat du mode Active": "On", "ACTIVE - Live": 133, "Mode de regulation": "Dynamique", "Mode ECO": "On", "Silence": "Off", "Mode Chronotermostato": "On", "TEMP - Consigne": 23.0, "TEMP - Boiler": 70, "TEMP - Carte mere": 27.0, "Puissance Active": "Puissance 1", "Heure du poele (0-23)": 9, "Minutes du poele (0-29)": 10, "Jour du poele (1-31)": 7, "Mois du poele (1-12)": 2, "Annee du poele": 2022, "Heures de fonctionnement total (s)": "84:9:25:5", "Heures de fonctionnement en puissance 1 (s)": "48:8:5:22", "Heures de fonctionnement en puissance 2 (s)": "11:8:20:1", "Heures de fonctionnement en puissance 3 (s)": "3:1:11:3", "Heures de fonctionnement en puissance 4 (s)": "0:15:31:19", "Heures de fonctionnement en puissance 5 (s)": "1:22:34:33", "Heures avant entretien": 0, "Minutes avant extinction": 0, "Nombre d'allumages": 1021, "Sonde Pellets": "Sonde pas active", "Effet sonore": "Off", "Etat effets sonores": "Off", "Sleep": "Off", "Mode": "Hiver", "Sonde wifi temperature 1": 255, "Sonde wifi temperature 2": 255, "Sonde wifi temperature 3": 255, "Inconnu": 255, "Set Puffer": 64, "Set Boiler": 50, "Set Health": 255, "Temperature retour": 255, "Antigel": "On"}
2022-02-07 08:58:55,133 :engineio.client :: INFO :: Sending packet PING data None
2022-02-07 08:58:55,186 :engineio.client :: INFO :: Received packet PONG data None
2022-02-07 08:59:20,137 :engineio.client :: INFO :: Sending packet PING data None
2022-02-07 08:59:20,188 :engineio.client :: INFO :: Received packet PONG data None
2022-02-07 08:59:45,140 :engineio.client :: INFO :: Sending packet PING data None
2022-02-07 08:59:45,186 :engineio.client :: INFO :: Received packet PONG data None
2022-02-07 09:00:10,144 :engineio.client :: INFO :: Sending packet PING data None
2022-02-07 09:00:10,206 :engineio.client :: INFO :: Received packet PONG data None

**Comment by PeterKalel** [comment]
@SebLz apparemment l'addon Portainer n'est plus accessible de ce que je comprend sur le github
 https://github.com/hassio-addons/addon-portainer

**Comment by SebLz** [comment]
> @SebLz apparemment l'addon Portainer n'est plus accessible de ce que je comprend sur le github https://github.com/hassio-addons/addon-portainer

C'est nouveau (et décevant), mais il y a déjà des forks apparemment:
https://github.com/alexbelgium/hassio-addons/tree/master/portainer

**Comment by SkyPhilHome** [comment]
Il semble que le problème soit la connexion avec le broker MQTT

`File "/maestro/cloud/maestro.py", line 237, in
client.connect(_MQTT_ip, _MQTT_port)
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
return self.reconnect()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
sock = self._create_socket_connection()
File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
raise err
File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
**ConnectionRefusedError: [Errno 111] Connection refused**
`

**ConnectionRefusedError: [Errno 111] Connection refused**
Problème de config peut-être ? IP et/ou port du broker ?  User/password ?

**Comment by PeterKalel** [comment]
C'est bon tout fonctionne effectivement c'était bien mon serveur MQTT qui déconnait 

Merci encore pour votre aide
